name: restaurant_task
description: "A Flutter restaurant mobile app with authentication, menu display, and cart functionality."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  equatable: ^2.0.5
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  email_validator: ^2.1.17
  intl: ^0.19.0
  go_router: ^12.1.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.4
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
